FROM ubuntu

ENV TZ=France/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update -y
RUN apt-get install -y curl unzip

RUN apt install software-properties-common -y
RUN add-apt-repository --yes --update ppa:ansible/ansible
RUN apt install ansible -y

RUN useradd --create-home -s /bin/bash ansible
RUN echo -n 'ansible:ansible' | chpasswd
RUN echo 'ansible ALL = NOPASSWD: ALL' > /etc/sudoers.d

USER ansible

CMD ["tail", "-f", "/dev/null"]
