FROM python:alpine

RUN apk update && apk add --no-cache python3 musl-dev libffi-dev openssl-dev make gcc python py2-pip python-dev
RUN pip install cffi
RUN pip install ansible

CMD ["tail", "-f", "/dev/null"]
